exports.globalLexicon = {
    "play" : { "tk": 0x01, "name": "PLAY", "cls": "function", "length": 0, "arity": 0 },
    "grid" : { "tk": 0x01, "name": "GRID", "cls": "function", "length": 2, "arity": 2 },
    "size" : { "tk": 0x01, "name": "SIZE", "cls": "function", "length": 2, "arity": 2 },
    "spacing" : { "tk": 0x01, "name": "SPACING", "cls": "function", "length": 2, "arity": 2 },
    "goal" : { "tk": 0x01, "name": "GOAL", "cls": "function", "length": 2, "arity": 2 },
    "seed" : { "tk": 0x01, "name": "SEED", "cls": "function", "length": 2, "arity": 2 },
    "mode" : { "tk": 0x01, "name": "MODE", "cls": "function", "length": 2, "arity": 2 },
    "rounding" : { "tk": 0x01, "name": "ROUND", "cls": "function", "length": 2, "arity": 2 },
    "tilecolor" : { "tk": 0x01, "name": "TILECOLOR", "cls": "function", "length": 2, "arity": 2 },
    "rgb" : { "tk": 0x01, "name": "RGB", "cls": "function", "length": 3, "arity": 3 },
    "style" : { "tk": 0x01, "name": "STYLE", "cls": "function", "length": 2, "arity": 2},
    "title" : { "tk": 0x01, "name": "TITLE", "cls": "function", "length": 2, "arity": 2},
    "description" : { "tk": 0x01, "name": "DESCRIPTION", "cls": "function", "length": 2, "arity": 2},
    "score" : { "tk": 0x01, "name": "SCORE", "cls": "function", "length": 1, "arity": 1},
    "button" : { "tk": 0x01, "name": "BUTTON", "cls": "function", "length": 2, "arity": 2},
}
